config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'
  get 'users/new'
  get 'sessions/new'

  get '/home',      to: 'static_pages#home'
  get '/about',     to: 'static_pages#about'
  get '/help',      to: 'static_pages#help'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/attend_event',   to: 'events#attend'
  delete '/unattend_event', to: 'events#unattend'
  get '/42', to: 'users#disp_42'
  post 'events/:id', to: 'comments#create'
  get '/by_category/:q', to: 'events#by_category'
  resources :comments
  resources :users
  resources :events
  resources :categories
end

app/models/event.rb
class Event < ApplicationRecord
    has_and_belongs_to_many :categories
    accepts_nested_attributes_for :categories

    has_and_belongs_to_many :users
    has_many :comments, dependent: :destroy
    has_many :ratings,  dependent: :destroy

    validates :title, presence: true, length: { maximum: 50 }
    validates :location, presence: true, length: { minimum: 2}
    validates :desc, presence: true, length: { maximum: 255 }
    validates :price, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
        @categories = Category.all
    end

    def create
        @event = Event.new(event_params)
        @categories = Category.all
        if @event.save
            redirect_to events_url
        end
    end
    
    def edit
        @event = Event.find(params[:id])
        @categories = Category.all
    end

    def update
        @event = Event.find(params[:id])
        p @event.date
        if @event.update(event_params)
            flash[:success] = "Event updated"
            redirect_to events_url
        else
            render 'edit'
        end
    end

    def destroy
        Event.find(params[:id]).destroy
        flash[:success] = "Event deleted"
        redirect_to events_url
    end

    def attend
        @event = Event.find(params[:format])
        if !current_user.events.include?(@event)
            current_user.events.push(@event)
        else
            flash[:danger] = "already attending to that event"
        end
        redirect_to request.referrer
    end

    def unattend
        @event = Event.find(params[:format])
        current_user.events.delete(@event)
        redirect_to request.referrer
    end

    def by_category
        query = params[:q]
        @category = query
        search = "SELECT * FROM events AS e
                        WHERE e.id IN (SELECT ce.event_id FROM categories_events AS ce
                        WHERE ce.category_id=(SELECT c.id FROM categories AS c
                        WHERE c.name='#{query}'))" 
        @events = Event.find_by_sql(search)
    end

    private
    def event_params
        params.require(:event).permit(:title, :location, :date, :desc, :price, :image_name, :category_ids => [])
    end

    def logged_in_user
      unless logged_in? 
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/views/events/_event.html.erb
<div class=" card event">
    <h4 class="card-title snow">
        <%= link_to event.title.upcase, event, class: 'link snow' %>
        <% if current_user.admin? %>
            (<%= event.id %>)
        <%end%>
    </h4>
    <h6 class="card-text snow"><%= event.location.upcase %></h6>

    <%begin%>
        <%= link_to image_tag("#{event.image_name}.jpg", class: "card-img-top"), event%>
    <%rescue%>
    <%end%>
    <div class="card-body">
        <%begin%>
            <div class="categories">
                <p class="snow rm-margin">categories: </p>
                <% event.categories.each do |cat|%>
                    <%= link_to cat.name,  "/by_category/#{cat.name}", class: 'link snow event-category'%>
                <%end%>
            </div>
        <%end%>
        <div class="flex-row evenly">
            <h5 class="card-subtitle mb-2 text-muted">$<%= event.price %></h5>
            <h6 class="card-text date"><%= event.date.strftime("%d-%m-%Y") %></h6>
        </div>

        <div class="btn-row">
            <% if current_user.admin? %>
                <%= link_to "edit", edit_event_path(event.id), class: 'card-link link edit_btn editbtn'%>
                <%= link_to "delete", event, method: :delete,
                                            data: { confirm: "You sure?" }, class: 'card-link link delete_btn deluser' %>
            <%end%>
            <%if  !current_user.events.include?(event) %>
                <%= link_to "save", attend_event_path(event.id), method: :post, class: 'card-link link save_btn showuser' %>
            <% else %>
                <%= link_to "unsave", unattend_event_path(event.id), method: :delete, class: 'card-link link save_btn showuser' %>
            <%end%>
        </div>

        <%if  current_user.events.include?(event) %>
            <div class="rating">
                <%= render :partial => 'ratings/form', locals: {user_id: current_user.id, event_id: event.id} %>
            </div>
        <%end%>
    </div>
</div>

app/views/events/_events.html.erb
<div class="container-pag">
	<div class="row-title">
		<section class="event-section">
		<div id= "cont-event">
			  <div class="evento-header snow">
			  	<h1>Events</h1>
  				<% if current_user.admin? %>
     	 				<%= link_to "Add New Event", new_event_path, class: 'link btn btn-primary btns ml-4 showuser" style="height: 45px;position:absolute; left:700px;' %>
  				<%end%>
  			</div>
			<%if @events.count > 0%>
				<section class="all_events">
					<% @events.each do |event| %>
						<%= render event %>
					<%end%>
				</section>
			<%end%>
		</div>
</section>
		<div class="categoria">
			<%= render :partial => '/categories/categories'%>
		</div>
	</div>
</div>

app/views/events/_form.html.erb
  <%begin%>
  <%= image_tag("#{@event.image_name}.jpg", class: "event_img") %>
  <%rescue%>
  <%end%>
<%= form_with(model: @event, local: true) do |f| %>

    <%= f.label :title, class:"snow" %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :location, class:"snow" %>
    <%= f.text_field :location, class: 'form-control' %>

    <%= f.label :date, class:"snow" %>
    <%= f.date_field :date, class: 'form-control' %>
    
    <%= f.label :desc, class:"snow" %>
    <%= f.text_area :desc, class: 'form-control' %>

    <%= f.label :price, class:"snow"%>
    <%= f.number_field :price, class: 'form-control' %>

    <%= f.label :image_name, class:"snow" %>
    <%= f.text_field :image_name, class: 'form-control' %>

    <% list = [] %>
    <% @event.categories.each do |b| %>
      <div><%list.push(b.name)%></div>
    <%end%>

    <h3 class="snow">event categories</h3>
    <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |b| %>
      <div class="snow"><%= b.check_box({checked: list.include?(b.text)}) %><%=  b.label {b.text}%></div>
    <%end%>

    <%= f.submit yield(:button_text), class: "btn btn-primary showuser" %>
      
  <% end %>
  

app/views/events/by_category.html.erb
<%= render 'events' %>

app/views/events/edit.html.erb
<%provide(:button_text,'Update Event')%>

<div class="col-md-6 col-md-offset-3 m-auto">
  <h1 class="snow">Edit event</h1>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<%= render 'events' %>

app/views/events/new.html.erb
<%provide(:button_text,'Create Event')%>
<%provide(:categories, @categories)%>

<div class="row">
  <div class="col-md-6 col-md-offset-3 m-auto">
    <h1 class="snow">Add a new event</h1>
    <%= render 'form'%>
  </div>
</div>

app/views/events/show.html.erb
<section class="show_event">
  <section class="event_section">
    <div class="col col-md-6">
    <div class="event_section">
    <h1 class="snow mt-3"><%= @event.title.upcase %></h1>
    
    <h3 class="snow"><%= @event.location.upcase %></h3>
    <div>
      <%= image_tag("#{@event.image_name}.jpg", class: "show-img") %>
      <div class="flex-row under-img">
        <h2 class="text-muted">$<%= @event.price %></h2>
        <h3 class="date"><%= @event.date.strftime("%d-%m-%Y") %></h3>
      </div>
    </div>
    <div class="media-body ml-3">
      
      
      <h4 class="snow" style="margin-top: 25px;font-weight: bold;background-color:#2e3440; width:160px;padding: 5px 10px 5px 10px;">Description</h4>
      <h6 class="snow" style="margin: 25px 0px 40px 0px;"><%= @event.desc %></h6>

      <h4 class="snow" style="margin-top: 25px;font-weight: bold;background-color:#2e3440; width:160px;padding: 5px 10px 5px 10px">Categories</h4>
      <div class="cont-cat">
      <% @event.categories.each do |cat| %>
        <div class="cat-each">
        <%= link_to cat.name, "/by_category/#{cat.name}", class: 'link snow' %>
        </div>
      <%end%>
      </div>

    </div>
    </div>
    </div>
  </section>

  <section class="comments">
    <h4 class="title snow">Comments</h4>
    <div class="row title">
    <% if @event.date < DateTime.now() || current_user.admin? %>
        <%= render :partial => 'comments/form', locals: {user_id: current_user.id, event_id: @event.id} %>
    <%end%>
    </div>
    <%= render @event.comments %>
  </section>
</section>