config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'
  get 'users/new'
  get 'sessions/new'

  get '/home',      to: 'static_pages#home'
  get '/about',     to: 'static_pages#about'
  get '/help',      to: 'static_pages#help'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/attend_event',   to: 'events#attend'
  delete '/unattend_event', to: 'events#unattend'
  get '/42', to: 'users#disp_42'
  post 'events/:id', to: 'comments#create'
  get '/by_category/:q', to: 'events#by_category'
  resources :comments
  resources :users
  resources :events
  resources :categories
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
<div class="container-fluid">
<a class="navbar-brand" href="/events">Eventure</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
  <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
    <li class="nav-item">
      <a id="nav-events" class="nav-link" aria-current="page" href="/events">Events</a>
    </li>

 <% if logged_in? %>
      
          <li class="nav-item"><%=link_to"Users", users_path, class: 'nav-link', id: "nav-users" %></li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%=link_to"Settings", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out!", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: 'nav-link' %></li>
        <% end %>

  </ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body class="main-body">
    <%= render 'layouts/navbar' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <section id="content">
    <%= yield %>
    </section>
  </body>
<%= javascript_pack_tag 'navbar' %>
</html>